apiVersion: v1
kind: Pod
metadata:
  name: octoprotect-backend
  labels:
    app: octoprotect-backend
spec:
  containers:
    - name: octoprotect-backend
      image: git.uwaterloo.ca:5050/octoprotect/backend:IMAGE_TAG
      imagePullPolicy: IfNotPresent
      env:
        - name: DB_TYPE
          value: "sqlite"
        - name: SQLITE_PATH
          value: "/persistent/app.db"
        - name: HTTP_LISTEN_ADDR
          value: "0.0.0.0:8080"
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: octoprotect-secret
              key: JWT_SECRET_KEY
        - name: PUSHOVER_TOKEN
          valueFrom:
            secretKeyRef:
              name: octoprotect-secret
              key: PUSHOVER_TOKEN
        - name: MAX_RETRY_NOTIFY
          valueFrom:
            configMapKeyRef:
              name: octoprotect-config
              key: MAX_RETRY_NOTIFY
        - name: ADMIN_TOKEN_BCRYPT_BASE64
          valueFrom:
            secretKeyRef:
              name: octoprotect-secret
              key: ADMIN_TOKEN_BCRYPT_BASE64
        - name: TELEGRAM_TOKEN
          valueFrom:
            secretKeyRef:
              name: octoprotect-secret
              key: TELEGRAM_TOKEN
      ports:
        - containerPort: 8080
          name: backend
      resources:
        limits:
          cpu: 50m
          memory: 128Mi
      volumeMounts:
        - mountPath: /persistent
          name: data
  restartPolicy: Always
  imagePullSecrets:
    - name: uw-pullsecret
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: octoprotect-data
